### ISSUE TITLE
Connection to Prometheus refused

### ISSUE THREAD

**Issue by DaCHack** [terjesannum/tibber-exporter#7]
I run the docker-compose file on Portainer/Docker on a Raspberry Pi and adapted the compose-file slightly for that reason:

```
version: "3.9"

services:

  tibber-exporter:
    container_name: tibber-exporter
    image: ghcr.io/terjesannum/tibber-exporter:latest
    ports:
      - "8806:8080"
    networks:
      - prometheus
    environment:
      TIBBER_TOKEN: XXX
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.47.0
    volumes:
      - /root/containers/tibber/prometheus.yml:/etc/prometheus/prometheus.yml
      - /root/containers/tibber/prometheus:/prometheus
    ports:
      - "8807:9090"
    networks:
      - prometheus
    restart: unless-stopped
    user: "0"

  grafana:
    container_name: grafana
    image: grafana/grafana:10.1.1
    volumes:
      - /root/containers/tibber/datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - /root/containers/tibber/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - /root/containers/tibber/dashboard.json:/dashboard.json
      - /root/containers/tibber/dashboard-without-pulse.json:/dashboard-without-pulse.json
      - /root/containers/tibber/dashboard-prices.json:/dashboard-prices.json
      - /root/containers/tibber/grafana.sh:/grafana.sh
      - /root/containers/tibber/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - prometheus
    entrypoint:
      - /grafana.sh
    environment:
      GF_INSTALL_PLUGINS: marcusolsson-hourly-heatmap-panel 2.0.1,marcusolsson-json-datasource 1.3.6
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Editor
    restart: unless-stopped
    user: "0"
    
networks:
  prometheus:
    internal: true
```

tibber-exporter and grafana seem to work fine, but I do not see any data coming into grafana and grafana logs tell me:

`logger=context userId=1 orgId=1 uname=admin t=2023-10-23T22:36:24.381211442Z level=error msg="Failed to call resource" error="error querying resource: Get \"http://prometheus:8807/api/v1/series?match%5B%5D=tibber_home_info&start=xxx&end=xxx\": dial tcp 172.23.0.2:8807: connect: connection refused" traceID=`

Also in the console, Prometheus cannot resolve tibber-exporter nor grafana:
```
/prometheus # nslookup tibber-exporter
Server:         127.0.0.11
Address:        127.0.0.11:53

Non-authoritative answer:

*** Can't find tibber-exporter: No answer
```

Any idea what is wrong with Prometheus not responding to grafana requests?
